### ISSUE TITLE
Unable to figure out how to use this addon

### ISSUE THREAD

**Issue by JyanseiCoding** [d4kir92/CVARs#1]
I can't find any way to use this. /Cvars doesn't work. Can't find any option in the settings.

**Comment by d4kir92** [comment]
/cvars should work or pressing on the minimap button

**Comment by d4kir92** [comment]
![image](https://github.com/d4kir92/CVARs/assets/23246564/13547ab9-646e-4457-9202-60b46d7eaba6)

**Comment by d4kir92** [comment]
![image](https://github.com/d4kir92/CVARs/assets/23246564/2ca52e3c-7d8d-48ec-9f14-714c66271dbc)

**Comment by JyanseiCoding** [comment]
I updated my addons and I see it now. Thank you! 

I'll be closing this.
